#!/bin/bash

#test_integer2 : evaluate the value of an integer
#This one is for ch 27

INT=-5

if [[ "$INT" =~ ^-?[0-9]+$ ]]; then
  if [ "$INT" -eq  0 ]; then
	echo "INT is zero."
  else
	if [ "$INT" -lt 0 ]; then
		echo "INT is negative."
	else
		echo "INT is positive."
	fi
	if [ $((INT % 2)) -eq 0 ]; then
		echo "INT is even."
	else 
		echo "INT is odd."
	fi
  fi
else 
  echo "INT is not an integer." >&2
  exit 1
fi

